const fs = require('fs');
const path = require('path');

const kuTips = [
    "ئاوی زۆر بخۆرەوە بۆ تەندروستی پێست و پاراستنی گورچیلەکان لە بەرد.",
    "ڕۆژانە لانی کەم ٣٠ خولەک بە خێرایی بڕۆ بۆ پاراستنی دڵ.",
    "خەوی تەواو لە نێوان ٧ بۆ ٨ کاتژمێر یارمەتی بەهێزکردنی مێشک دەدات.",
    "دوورکەوە لە شەکر بۆ ڕێگری لە قەڵەوی و شەکرە.",
    "خواردنی سەوزەوات ڤیتامینە پێویستەکان دابین دەکات.",
    "کەمکردنەوەی خوێ پەستانی خوێنت بە جێگیری دەهێڵێتەوە.",
    "شوشتنی دەستەکان بە ڕێکوپێکی باشترینە بۆ خۆپاراستن لە نەخۆشی.",
    "یاسای ٢٠-٢٠-٢٠ بەکاربهێنە بۆ حەسانەوەی چاوەکانت لە کاتی بەکارهێنانی شاشە.",
    "ڕۆژانە دوو جار ددانەکانت بشۆ.",
    "هەڵکێشانی هەناسەی قووڵ یارمەتی کەمکردنەوەی دڵەڕاوکێ دەدات.",
    "ژەمی بەیانیان مەپەڕێنە چونکە وزەی ڕۆژەکەت دەدات.",
    "دوورکەوە لە خواردنە لەقوتووکراوەکان.",
    "دژەخۆر بەکاربهێنە بۆ پاراستنی پێستت لە تیشکی خۆر.",
    "لەکاتی دانیشتن پشتی خۆت ڕاست ڕابگرە.",
    "پەیژە بەکاربهێنە لەبری بەرزکەرەوە.",
    "پێش کڕینی خواردن پێکهاتەکانی بخوێنەوە.",
    "تێکەڵاوبوونی کۆمەڵایەتی تەندروستی دەروونیت باشتر دەکات.",
    "لە جگەرەکێشان دوورکەوە.",
    "دوای ئێوارە کافایین کەم بکەرەوە بۆ خەوێکی باشتر.",
    "ساڵانە پشکنینی گشتی بکە.",
    "چای سەوز بخۆرەوە بۆ خێراکردنی مێتابۆلیزم.",
    "خواردنی دەوڵەمەند بە ڕیشاڵ کۆئەندامی هەرست چالاک دەکات.",
    "چەورییە تەندروستەکان بخۆ وەکو زەیتی زەیتوون.",
    "کالسیۆم و ڤیتامین D وەربگرە بۆ ئێسکەکان.",
    "گوێ لە جەستەت بگرە و کاتی پێویست پشوو بدە.",
    "لە کاتی وەرزشدا ئاو زۆر بخۆرەوە.",
    "دەرمانەکان لە شوێنی فێنک و وشک هەڵبگرە.",
    "مۆبایلەکەت بەردەوام پاک بکەرەوە.",
    "ئەگەر کارت دانیشتنە، زوو زوو هەستە و پیاسە بکە.",
    "پێش خەوتن دوورکەوە لە شاشەی مۆبایل.",
    "خواردنەکانت بە هێواشی بخۆ و باش بیجوو.",
    "چەرەسات بخۆ لەبری چپس.",
    "دوای نانخواردن کەمێک پیاسە بکە.",
    "لە سەرما خۆت گەرم دابپۆشە.",
    "خواردنی ماسی بۆ مێشک بەسوودە.",
    "بەردەوام کتێب بخوێنەوە بۆ چالاککردنی مێشک.",
    "ئەڤۆکادۆ بخۆ بۆ تەندروستی دڵ.",
    "لە کاتی توڕەیی بڕیار مەدە.",
    "کاتی تایبەت بۆ خۆت تەرخان بکە.",
    "بەزەییت بە خۆتدا بێتەوە و خۆت خۆشبوێت.",
    "دوورکەوە لە خواردنەوە گازییەکان.",
    "پێڵاوی گونجاو لەپێ بکە بۆ ڕێگری لە ئازاری پشت.",
    "گۆشتی سوور کەم بکەرەوە.",
    "بەیانیان ئاوی شلەتێن لەگەڵ لیمۆ بخۆرەوە.",
    "ماست بخۆ بۆ تەندروستی ڕیخۆڵەکان.",
    "لەبەر خۆر کڵاو لەسەر بکە.",
    "چەوری زگ کەم بکەرەوە بە وەرزش.",
    "زنجەفیل بۆ هێورکردنەوەی گەدە باشە.",
    "سیر بەرگری لەش بەهێز دەکات.",
    "شەوانە زوو بخەوە.",
    "بەیانیان زوو هەستە.",
    "پێش نووستن قاوە مەخۆرەوە.",
    "مەساجکردن سووڕی خوێن چالاک دەکات.",
    "پێنین تەندروستی دڵ باشتر دەکات.",
    "خواردنی توو و شاتوو بۆ مێشک بەسوودە.",
    "شوتی بخۆ بۆ نەهێشتنی تینوێتی.",
    "بەردەوام خۆت بپارێزە لە تیشکی سەرووی بنەوشەیی.",
    "بەردەوام پشکنینی چاو بکە.",
    "کیسەی ئاوی گەرم بۆ ئازاری ماسولکە بەکاربهێنە.",
    "سەوزە گەڵا تاریکەکان ئاسنی زۆریان تێدایە.",
    "ڕۆژانە گوێز بخۆ بۆ پاراستنی خانەکانی مێشک.",
    "دوورکەوە لە گوێگرتن لە مۆسیقای زۆر بەرز.",
    "خواردنی برۆکلی ڕێگری لە هەوکردن دەکات.",
    "ئاگاداری کێشی خۆت بە.",
    "کەمکردنەوەی کاربۆهیدرات یارمەتی دابەزاندنی کێش دەدات.",
    "سپیناخ ڤیتامین K تێدایە بۆ خوێن مەین.",
    "دارچین یارمەتی ڕێکخستنی شەکرەی خوێن دەدات.",
    "مۆز باشترین سەرچاوەی پۆتاسیۆمە بۆ ماسولکەکان.",
    "کەمتر خواردنی برژاو بخۆ بۆ ڕێگری لە شێرپەنجە.",
    "هەمیشە دەستەکانت پێش نانخواردن بشۆ.",
    "میوەی فرێش باشترە لە شەربەتی میوە.",
    "پێکەنین یارمەتی کەمکردنەوەی هۆرمۆنی فشار دەدات.",
    "خەوی نیوەڕۆ بۆ ٢٠ خولەک وزەت پێدەداتەوە.",
    "بۆ ئازاری سەر، ئاوی زۆر بخۆرەوە.",
    "گێزەر باشە بۆ بینینی چاو.",
    "فشار مەخەرە سەر چاوەکانت لە تاریکیدا.",
    "گرنگی بە پاکوخاوێنی کەسی بدە.",
    "بۆنخۆشکەرە سروشتییەکان بەکاربهێنە.",
    "خۆت دوور بگرە لە کەسانی نەرێنی.",
    "بەردەوام ئاو بەسەر دەموچاوتدا بکە.",
    "بەپێی پێویست ئاو بدە بە ڕووەکەکانی ماڵەوە.",
    "خوێندنەوەی پێش خەوتن یارمەتیت دەدات خێراتر بخەویت.",
    "بۆکسێن و وەرزشەکانی تر بۆ کەمکردنەوەی فشار باشە.",
    "ڕۆژانە مێوژ بخۆ بۆ بەهێزکردنی بیرەوەری.",
    "لە کاتی کارکردن زوو زوو پشوو بدە.",
    "ماسی سەلەمۆن زۆر باشە بۆ دڵ.",
    "خەوی باش باشترین چارەسەرە بۆ پێست.",
    "هەمیشە هیوادار بە و گەشبین بە.",
    "دوورکەوە لە خواردنی خێرا (Fast Food).",
    "تەماتە دژە ئۆکسانی لایکۆپینی تێدایە کە زۆر بەسوودە."
];

const enTips = [
    "Drink plenty of water for skin health and to protect your kidneys.",
    "Walk briskly for at least 30 minutes daily to protect your heart.",
    "Get 7-8 hours of sleep to boost your brain.",
    "Avoid sugar to prevent obesity and diabetes.",
    "Eating vegetables provides essential vitamins.",
    "Reducing salt keeps your blood pressure stable.",
    "Washing hands regularly is the best prevention against diseases.",
    "Use the 20-20-20 rule to rest your eyes from screens.",
    "Brush your teeth twice daily.",
    "Taking deep breaths helps reduce anxiety.",
    "Don't skip breakfast as it gives you energy for the day.",
    "Avoid canned foods.",
    "Use sunscreen to protect your skin from the sun.",
    "Keep your back straight while sitting.",
    "Use stairs instead of the elevator.",
    "Read ingredients before buying food.",
    "Socializing improves your mental health.",
    "Avoid smoking.",
    "Reduce caffeine after the afternoon for better sleep.",
    "Do an annual general checkup.",
    "Drink green tea to speed up metabolism.",
    "Eating fiber-rich food makes digestion active.",
    "Eat healthy fats like olive oil.",
    "Get calcium and vitamin D for your bones.",
    "Listen to your body and rest when needed.",
    "Drink plenty of water during exercise.",
    "Keep medicines in a cool, dry place.",
    "Continuously clean your mobile phone.",
    "If your work involves sitting, stand up and walk frequently.",
    "Avoid mobile screens before sleeping.",
    "Eat slowly and chew your food well.",
    "Eat nuts instead of chips.",
    "Take a short walk after eating.",
    "Dress warmly in cold weather.",
    "Eating fish is beneficial for the brain.",
    "Continuously read books to stimulate your brain.",
    "Eat avocado for heart health.",
    "Don't make decisions when angry.",
    "Dedicate special time for yourself.",
    "Be kind to yourself and love yourself.",
    "Avoid carbonated drinks.",
    "Wear proper shoes to prevent back pain.",
    "Reduce red meat consumption.",
    "Drink warm water with lemon in the morning.",
    "Eat yogurt for gut health.",
    "Wear a hat under the sun.",
    "Reduce belly fat through exercise.",
    "Ginger is good for soothing the stomach.",
    "Garlic strengthens the immune system.",
    "Sleep early at night.",
    "Wake up early in the morning.",
    "Don't drink coffee before sleeping.",
    "Massaging activates blood circulation.",
    "Laughing improves heart health.",
    "Eating berries is good for the brain.",
    "Eat watermelon to quench thirst.",
    "Always protect yourself from UV rays.",
    "Regularly check your eyes.",
    "Use a hot water bag for muscle pain.",
    "Dark leafy greens contain a lot of iron.",
    "Eat walnuts daily to protect brain cells.",
    "Avoid listening to very loud music.",
    "Eating broccoli prevents inflammation.",
    "Take care of your weight.",
    "Reducing carbs helps in weight loss.",
    "Spinach contains Vitamin K for blood clotting.",
    "Cinnamon helps regulate blood sugar.",
    "Bananas are the best source of potassium for muscles.",
    "Eat less grilled/charred food to prevent cancer.",
    "Always wash your hands before eating.",
    "Fresh fruit is better than fruit juice.",
    "Laughing helps reduce stress hormones.",
    "A 20-minute nap gives you energy back.",
    "For headaches, drink lots of water.",
    "Carrots are good for eyesight.",
    "Don't strain your eyes in the dark.",
    "Pay attention to personal hygiene.",
    "Use natural fragrances.",
    "Keep yourself away from negative people.",
    "Frequently splash water on your face.",
    "Water your indoor plants as needed.",
    "Reading before bed helps you fall asleep faster.",
    "Boxing and other sports are good for reducing stress.",
    "Eat raisins daily to strengthen memory.",
    "Take frequent breaks while working.",
    "Salmon is very good for the heart.",
    "Good sleep is the best treatment for your skin.",
    "Always be hopeful and optimistic.",
    "Avoid fast food.",
    "Tomatoes contain the antioxidant lycopene, which is very beneficial."
];

const arTips = [
    "اشرب الكثير من الماء لصحة الجلد وحماية الكليتين من الحصى.",
    "امش بسرعة لمدة 30 دقيقة على الأقل يوميا لحماية قلبك.",
    "الحصول على 7-8 ساعات من النوم يساعد في تقوية الدماغ.",
    "تجنب السكر للوقاية من السمنة ومرض السكري.",
    "تناول الخضروات يوفر الفيتامينات الضرورية.",
    "تقليل الملح يحافظ على استقرار ضغط الدم.",
    "غسل اليدين بانتظام هو أفضل وقاية من الأمراض.",
    "استخدم قاعدة 20-20-20 لإراحة عينيك من الشاشات.",
    "نظف أسنانك مرتين يوميا.",
    "أخذ نفس عميق يساعد في تقليل القلق.",
    "لا تتخط وجبة الإفطار لأنها تمنحك طاقة لليوم.",
    "تجنب الأطعمة المعلبة.",
    "استخدم واقي الشمس لحماية بشرتك من الشمس.",
    "حافظ على استقامة ظهرك أثناء الجلوس.",
    "استخدم السلالم بدلا من المصعد.",
    "اقرأ المكونات قبل شراء الطعام.",
    "الاختلاط الاجتماعي يحسن صحتك العقلية.",
    "تجنب التدخين.",
    "قلل من الكافيين بعد الظهر لنوم أفضل.",
    "قم بإجراء فحص عام سنوي.",
    "اشرب الشاي الأخضر لتسريع الأيض.",
    "تناول الأطعمة الغنية بالألياف ينشط الهضم.",
    "تناول الدهون الصحية مثل زيت الزيتون.",
    "احصل على الكالسيوم وفيتامين د لعظامك.",
    "استمع لجسدك وارتح عند الحاجة.",
    "اشرب الكثير من الماء أثناء ممارسة الرياضة.",
    "احفظ الأدوية في مكان بارد وجاف.",
    "نظف هاتفك المحمول باستمرار.",
    "إذا كان عملك يتطلب الجلوس، قف وامش بشكل متكرر.",
    "تجنب شاشات الجوال قبل النوم.",
    "كل ببطء وامضغ طعامك جيدا.",
    "تناول المكسرات بدلا من رقائق البطاطس.",
    "خذ نزهة قصيرة بعد الأكل.",
    "ارتد ملابس دافئة في الطقس البارد.",
    "تناول الأسماك مفيد للدماغ.",
    "اقرأ الكتب باستمرار لتحفيز دماغك.",
    "تناول الأفوكادو لصحة القلب.",
    "لا تتخذ قرارات وأنت غاضب.",
    "خصص وقتا لنفسك.",
    "كن لطيفا مع نفسك وأحبها.",
    "تجنب المشروبات الغازية.",
    "ارتد أحذية مناسبة لمنع آلام الظهر.",
    "قلل من استهلاك اللحوم الحمراء.",
    "اشرب ماء دافئا مع ليمون في الصباح.",
    "تناول الزبادي لصحة الأمعاء.",
    "ارتد قبعة تحت الشمس.",
    "قلل من دهون البطن عن طريق ممارسة الرياضة.",
    "الزنجبيل جيد لتهدئة المعدة.",
    "الثوم يقوي جهاز المناعة.",
    "نم مبكرا في الليل.",
    "استيقظ مبكرا في الصباح.",
    "لا تشرب القهوة قبل النوم.",
    "التدليك ينشط الدورة الدموية.",
    "الضحك يحسن صحة القلب.",
    "تناول التوت مفيد للدماغ.",
    "تناول البطيخ لإرواء العطش.",
    "احم نفسك دائما من الأشعة فوق البنفسجية.",
    "افحص عينيك بانتظام.",
    "استخدم كيس ماء ساخن لآلام العضلات.",
    "الخضراوات الورقية الداكنة تحتوي على الكثير من الحديد.",
    "تناول الجوز يوميا لحماية خلايا الدماغ.",
    "تجنب الاستماع إلى الموسيقى الصاخبة جدا.",
    "تناول البروكلي يمنع الالتهابات.",
    "انتبه لوزنك.",
    "تقليل الكربوهيدرات يساعد في إنقاص الوزن.",
    "يحتوي السبانخ على فيتامين ك لتخثر الدم.",
    "القرفة تساعد في تنظيم سكر الدم.",
    "الموز هو أفضل مصدر للبوتاسيوم للعضلات.",
    "تناول أطعمة مشوية أقل للوقاية من السرطان.",
    "اغسل يديك دائما قبل الأكل.",
    "الفاكهة الطازجة أفضل من عصير الفاكهة.",
    "الضحك يساعد في تقليل هرمونات التوتر.",
    "قيلولة لمدة 20 دقيقة تعيد لك طاقتك.",
    "للصداع، اشرب الكثير من الماء.",
    "الجزر جيد للبصر.",
    "لا تجهد عينيك في الظلام.",
    "انتبه للنظافة الشخصية.",
    "استخدم العطور الطبيعية.",
    "ابتعد عن الأشخاص السلبيين.",
    "رش الماء على وجهك بشكل متكرر.",
    "اسق نباتاتك الداخلية حسب الحاجة.",
    "القراءة قبل النوم تساعدك على النوم بشكل أسرع.",
    "الملاكمة والرياضات الأخرى جيدة لتقليل التوتر.",
    "تناول الزبيب يوميا لتقوية الذاكرة.",
    "خذ فترات راحة متكررة أثناء العمل.",
    "السلمون مفيد جدا للقلب.",
    "النوم الجيد هو أفضل علاج لبشرتك.",
    "كن دائما متفائلا ومفعما بالأمل.",
    "تجنب الوجبات السريعة.",
    "تحتوي الطماطم على اللايكوبين المضاد للأكسدة والمفيد جدا."
];

let jsCode = "const dailyTipsData = {\n";
jsCode += "    ku: " + JSON.stringify(kuTips, null, 8) + ",\n";
jsCode += "    en: " + JSON.stringify(enTips, null, 8) + ",\n";
jsCode += "    ar: " + JSON.stringify(arTips, null, 8) + "\n};\n";

const targetPath = path.join(__dirname, 'js/data/others.js');
let existing = fs.readFileSync(targetPath, 'utf8');
existing += "\n" + jsCode;
fs.writeFileSync(targetPath, existing);
console.log('Appended dailyTipsData to others.js');
